#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiggsApi.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Mobitrans")]
	public partial class MobitransDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public MobitransDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MobitransConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MobitransDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MobitransDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MobitransDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MobitransDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FN_SecondsSinceLastRecentVisit_ByIP", IsComposable=true)]
		public System.Nullable<int> FN_SecondsSinceLastRecentVisit_ByIP([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IP", DbType="NVarChar(15)")] string iP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Recency", DbType="Int")] System.Nullable<int> recency)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iP, recency).ReturnValue));
		}
	}
}
#pragma warning restore 1591
